### ISSUE TITLE
Rethink hook execution concept

### ISSUE THREAD

**Issue by nicholasjng** [appliedAI-Initiative/lakefs-spec#113]
The more I think about it, the more I am unsure about our "execute hooks anyway after events" approach. 

Because, what is the point of creating a commit if a file upload fails? As of now, this is only not exploding on us because we provide the "if diff is empty, abort" escape hatch.

Would it not be more sensible to execute hooks only after operational success? Opinions welcome.

**Comment by AdrianoKF** [comment]
I see value in having a hook be called in case of errors as well. For example, one could implement some cleanup logic, notifications, etc.

What would be useful for hook writers in these cases is receiving any errors as part of the hook context, so they can be examined in the hook.

**Comment by nicholasjng** [comment]
Closing, as hooks were removed in #139.
