### ISSUE TITLE
Discuss optional `PyYAML` dependency

### ISSUE THREAD

**Issue by AdrianoKF** [appliedAI-Initiative/lakefs-spec#141]
I disagree - has any user reported any headaches? With all due respect, running `pip install --upgrade pyyaml` once in the console (which is even suggested if you fail to load an existing configfile) is possible for every prospective user of this library.

And since we only require it for an opt-in feature (lakectl configs), adding at as an unconditional requirement is not appropriate.

That being said, if we mention it heavily in the user guide, we can either a) change that to use other auth methods or b) put a small disclaimer in front of the examples (preferred).

_Originally posted by @nicholasjng in https://github.com/appliedAI-Initiative/lakefs-spec/pull/129#discussion_r1380367944_

**Comment by janwillemkl** [comment]
I actually would prefer option A.

* If you have not downloaded your config file as part of the setup, there is no way to download it again. I could also not find documentation on the structure of the file to create one manually.
* The quickstart is the first contact with the library, make it as easy to get it up and running.

**Comment by AdrianoKF** [comment]
Based on a discussion in a call with @nicholasjng, we'll be including the dependency going forward, since the auto-discovery is the default mechanism all docs rely on (and the least surprising behavior for users who have the file on their machine already).
