### ISSUE TITLE
Docs misrendering on development

### ISSUE THREAD

**Issue by nicholasjng** [appliedAI-Initiative/lakefs-spec#149]
Current HEAD version: https://lakefs-spec.org/0.3.1.dev14+gbc76a28/tutorials/demo_data_science_project/

I see the following problems:

- [ ] Bulleted markdown lists in the beginning are not rendered,
- [ ] Pandas DataFrame prints are written over the line.

If we decide to keep the output cells for the docs build, we should also add some information to the remaining print statements, just as we did to the data shapes and accuracies.

**Comment by AdrianoKF** [comment]
- The lists in Markdown cells render correctly for me when adding a blank line before the first list item:
  ```
  Foo:

  * Bar

  Instead of:
  * Bar
  ```
- Data frame rendering could be improved with a bit of custom CSS (ping me if you need help): https://github.com/greenape/mknotebooks/issues/24
