### ISSUE TITLE
Investigate breaking API change in `lakefs-client==0.108.0`

### ISSUE THREAD

**Issue by AdrianoKF** [appliedAI-Initiative/lakefs-spec#47]
As seen in this CI job, `lakefs-client==0.108.0` seems to include a breaking API change that we need to address: https://github.com/appliedAI-Initiative/lakefs-spec/actions/runs/6023343785/job/16340149959

# Acceptance Criteria

- [ ] Affected API call has been identified and updated
- [x] `lakefs-client` dependency has been unpinned in `pyproject.toml`
- [x] CI builds are passing

**Comment by nicholasjng** [comment]
Can confirm that the issue disappears when bumping the docker-compose file's `lakefs` image to `v0.108.0`, so this seems to be a version mismatch.

**Comment by AdrianoKF** [comment]
Closed by #50
